# action.yml
name: 'kustomize'
description: 'Kustomize your k8s in Github actions'
inputs:
  services:
    description: 'What to kustomize'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.services }}
